package cn.ykcryobs.ptportal.ui.theme

import androidx.compose.ui.graphics.Color

// Dark theme palette - deep charcoal base with warm copper accent
val DarkBase = Color(0xFF0E1114)
val DarkSurface = Color(0xFF15191D)
val DarkSurfaceContainer = Color(0xFF1C2126)
val DarkSurfaceContainerHigh = Color(0xFF242A30)
val DarkOnSurface = Color(0xFFDCE2E8)
val DarkOnSurfaceVariant = Color(0xFF8A939E)
val DarkOutline = Color(0xFF31383F)
val DarkPrimary = Color(0xFFE8954C)
val DarkOnPrimary = Color(0xFF1F1206)
val DarkPrimaryContainer = Color(0xFF3A2510)
val DarkOnPrimaryContainer = Color(0xFFF5C08A)
val DarkSecondary = Color(0xFF5CB8A6)
val DarkOnSecondary = Color(0xFF06231E)
val DarkSecondaryContainer = Color(0xFF1B3A33)
val DarkOnSecondaryContainer = Color(0xFF9BDCCD)
val DarkError = Color(0xFFE85D5D)
val DarkOnError = Color(0xFF2A0808)
val DarkErrorContainer = Color(0xFF3A1515)
val DarkOnErrorContainer = Color(0xFFF5A0A0)
val DarkTertiary = Color(0xFF7BA7DE)
val DarkOnTertiary = Color(0xFF0A1E33)

// Light theme palette - warm off-white with matching accent
val LightBase = Color(0xFFFAFAF8)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFF2F1EE)
val LightSurfaceContainerHigh = Color(0xFFEAE9E5)
val LightOnSurface = Color(0xFF1A1D21)
val LightOnSurfaceVariant = Color(0xFF5A6168)
val LightOutline = Color(0xFFD5D3CF)
val LightPrimary = Color(0xFFB86A20)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFDE8D0)
val LightOnPrimaryContainer = Color(0xFF6B3A05)
val LightSecondary = Color(0xFF2A7A68)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0F0E6)
val LightOnSecondaryContainer = Color(0xFF0A3830)
val LightError = Color(0xFFC63F3F)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFADAD5)
val LightOnErrorContainer = Color(0xFF6B1010)
val LightTertiary = Color(0xFF3A6AA8)
val LightOnTertiary = Color(0xFFFFFFFF)
